---
title: "데이터 탐색 & 전처리"
output: html_notebook
---

### 데이터 불러오기

---

* 경로에 맞는 파일 이름 목록 가져오기
```{r}
dir = "C:/data/health"

# 경로에서 패턴에 맞는 파일 이름 찾기
files <- list.files(path = dir, pattern = ".csv")
files
```

* 파일 이름 목록을 통해 데이터 불러오기
```{r}
file <- paste(dir, "/", files, sep = "")
data_list <- lapply(file, read_csv)
```
데이터가 작성된 연도마다 속성, 기준이 다르므로 전처리를 따로 진행

---

#### 2010 ~ 2013년 데이터 전처리
* 데이터 확인
```{r}
data_2010 <- data.frame(data_list[1])
head(data_2010)
```
```{r}
data_2011 <- data.frame(data_list[2])
head(data_2011)
```
```{r}
data_2012 <- data.frame(data_list[3])
head(data_2012)
```
```{r}
data_2013 <- data.frame(data_list[4])
head(data_2013)
```

+ 열 이름 변경 

전처리 편의, 병합을 위해 열 이름을 변경한다. 
```{r}
colName <- c("연도", "번호", "성별", "연령대", "지역", "신장", "체중", "허리", "좌시력", "우시력", "좌청력", "우청력", "수축혈압", "이완혈압", "공복혈당", "총콜레스테롤", "트리글리세라이드", "HDL콜레스테롤", "LDL콜레스테롤", "혈색소", "요단백", "혈청크레아티닌", "AST", "ALT", "감마지티피", "흡연", "음주", "구강검진", "치아우식증", "결손치", "치아마모증", "제3대구치", "치석", "공개일자")
names(data_2010) <- colName
names(data_2011) <- colName
names(data_2012) <- colName
names(data_2013) <- colName
```

  + 데이터 변경

2002 ~ 2013년의 데이터는 2014년 이후의 데이터와 연령대 코드가 다르다. 2014년 이후의 데이터 기준에 맞춰 2010 ~ 2013년의 데이터를 변경해야 한다. 
```{r}
for (i in 1:14){
  data_2010[data_2010$연령대 == i, "연령대"] = i + 4
  data_2011[data_2011$연령대 == i, "연령대"] = i + 4
  data_2012[data_2012$연령대 == i, "연령대"] = i + 4
  data_2013[data_2013$연령대 == i, "연령대"] = i + 4
}
head(data_2010)
```

##### 결측치 처리

+ 결측치 개수 확인(전처리 전)
```{r}
cat("2010년 데이터 결측치 개수 : ", sum(is.na(data_2010)), "개", "\n")
cat("2011년 데이터 결측치 개수 : ", sum(is.na(data_2011)), "개", "\n")
cat("2012년 데이터 결측치 개수 : ", sum(is.na(data_2012)), "개", "\n")
cat("2013년 데이터 결측치 개수 : ", sum(is.na(data_2013)), "개", "\n")
```

대부분의 결측치는 구강검진을 하지 않은 경우 관련 항목이 결측치로 처리된 경우, 검진 항목이 다른 경우 등에서 발생했다.
건강검진 데이터의 특성상, 다른 데이터와 관련이 있을 확률이 있으므로 다른 값으로 대체할 수 없다. 
따라서, "-" 기호를 사용해 결측치를 대체하였다. 
```{r}
data_2010[is.na(data_2010)] <- "-"
data_2011[is.na(data_2011)] <- "-"
data_2012[is.na(data_2012)] <- "-"
data_2013[is.na(data_2013)] <- "-"
```


* 결측치 개수 확인(전처리 후)
```{r}
cat("2010년 데이터 결측치 개수 : ", sum(is.na(data_2010)), "개", "\n")
cat("2011년 데이터 결측치 개수 : ", sum(is.na(data_2011)), "개", "\n")
cat("2012년 데이터 결측치 개수 : ", sum(is.na(data_2012)), "개", "\n")
cat("2013년 데이터 결측치 개수 : ", sum(is.na(data_2013)), "개", "\n")
```
